# Generated by Django 5.1.7 on 2026-10-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("gender", models.CharField(blank=True, max_length=40)),
                (
                    "college_tier",
                    models.CharField(
                        choices=[
                            ("TIER_1", "Tier 1"),
                            ("TIER_2", "Tier 2"),
                            ("TIER_3", "Tier 3"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("employer_brand", models.CharField(blank=True, max_length=160)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("consent_given", models.BooleanField(default=False)),
                ("self_reported", models.BooleanField(default=True)),
                ("is_sample_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("kaggle", "Kaggle"),
                            ("certificate", "Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("verification_code", models.CharField(blank=True, max_length=32)),
                ("ownership_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "handle", "url"),
                        name="unique_evidence_link",
                    )
                ],
            },
        ),
    ]
