# Generated by Django 5.1.7 on 2026-10-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence", models.FloatField()),
                ("baseline", models.FloatField()),
                ("delta", models.FloatField()),
                ("baseline_source", models.CharField(max_length=32)),
                ("warning", models.CharField(blank=True, max_length=300)),
                ("breakdown", models.JSONField(default=dict)),
                ("sources_used", models.JSONField(default=list)),
                ("sources_failed", models.JSONField(default=list)),
                ("ownership_verified", models.BooleanField(default=False)),
                ("is_sample_data", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_result",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
    ]
